project_id = "ghsxvotykfhnfqyymdvh"

[functions]
# Endpoints: /functions/v1/<name>
# En dev podemos dejar verify_jwt=false; en prod TRUE.
[functions.set_openai_key]
verify_jwt = false
[functions.create_order]
verify_jwt = false
[functions.sandbox_message]
verify_jwt = false
[functions.process_workflow_action]
verify_jwt = false
[functions.agent_intent]
verify_jwt = false
[functions.process_timers]
verify_jwt = false
[functions.call_openai]
verify_jwt = false
[functions.reset_tests]
verify_jwt = false
[functions.delete_order_complete]
verify_jwt = false
[functions.cleanup_all_data]
verify_jwt = false

[env]
APP_ENCRYPTION_KEY = "change-this-32bytes-minimo"